[package]
name = "messloc"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Port of Mesh Allocator"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.7"
libc = "0.2.126"
lazy_static = "1"

[features]
allocator-api = []
