[package]
name = "messloc"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Port of Mesh Allocator"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.7"
libc = "0.2.126"
once_cell = "1.13.0"
page_size = "0.4.2"
rand = "0.8.5"
spin = "0.9.4"
thread_local = "1.1.4"

[features]
allocator-api = []
