name: Run cargo check
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job triggered due to event"
      - run: echo "Job is now running on ${{ runner.os }}"
      - run: echo "Branch is ${{ github.ref }}, Repo is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "Repo ${{ github.repository }} cloned to VM"
      - run: echo "Job is ready for testing."
      - name: Run cargo check
        run: cargo check
      - run: echo "job's status is ${{ job.status }}."

